# Generated by Django 5.2.8 on 2025-11-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="onchaineventlog",
            new_name="indexer_onc_tx_hash_21f4cd_idx",
            old_name="indexer_onc_tx_hash_2_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaineventlog",
            new_name="indexer_onc_market__e055a2_idx",
            old_name="indexer_onc_market_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaineventlog",
            new_name="indexer_onc_event_n_215c16_idx",
            old_name="indexer_onc_event_name_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaineventlog",
            new_name="indexer_onc_user_ad_3f090d_idx",
            old_name="indexer_onc_user_address_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaintransaction",
            new_name="indexer_onc_tx_hash_b3b4e4_idx",
            old_name="indexer_onc_tx_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaintransaction",
            new_name="indexer_onc_network_e935d7_idx",
            old_name="indexer_onc_network_status_idx",
        ),
        migrations.RenameIndex(
            model_name="onchaintransaction",
            new_name="indexer_onc_block_n_62aa8b_idx",
            old_name="indexer_onc_block_number_idx",
        ),
    ]
