# Generated by Django 5.2.8 on 2025-11-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "indexer",
            "0002_rename_indexer_onc_tx_hash_2_idx_indexer_onc_tx_hash_21f4cd_idx_and_more",
        ),
        ("markets", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onchaineventlog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="onchaintransaction",
            options={},
        ),
        migrations.AddField(
            model_name="onchaineventlog",
            name="onchain_tx",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="indexer.onchaintransaction",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="onchaineventlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="onchaineventlog",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onchain_events",
                to="markets.market",
            ),
        ),
        migrations.AlterField(
            model_name="onchaintransaction",
            name="block_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="onchaintransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="onchaintransaction",
            name="network",
            field=models.CharField(default="sepolia", max_length=32),
        ),
        migrations.AlterField(
            model_name="onchaintransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
