# Generated by Django 5.2.8 on 2025-11-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0003_alter_onchaineventlog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onchaineventlog",
            name="onchain_tx",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="indexer.onchaintransaction",
            ),
        ),
    ]
