# Generated by Django 5.2.8 on 2025-11-16 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_markets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="markets",
                to="markets.marketcategory",
            ),
        ),
        migrations.AddField(
            model_name="outcometoken",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcome_tokens",
                to="markets.market",
            ),
        ),
        migrations.AddField(
            model_name="pricehistory",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="markets.market",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="market",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolution",
                to="markets.market",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="resolver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_markets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["status", "-created_at"], name="markets_mar_status_f5bebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["category", "status"], name="markets_mar_categor_1919dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outcometoken",
            index=models.Index(
                fields=["market", "outcome_type"], name="markets_out_market__5ac48b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="outcometoken",
            unique_together={("market", "outcome_type")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["market", "-timestamp"], name="markets_pri_market__bc52ef_idx"
            ),
        ),
    ]
